### ISSUE TITLE
C#封装darknet，如何使用gpu加速

### ISSUE THREAD

**Issue by lf2055828** [zhang8043/YoloWrapper#2]
现在可以执行代码，但是发现检测速度有点慢，一张图像要1.5秒左右，请问如何使用gpu加速！万分感谢！微信：18435742076！望您不吝赐教

**Comment by zhang8043** [comment]
你好，教程和代码中采用的是yolo_cpp_dll_no_gpu.sln生成的Dll，请采用yolo_cpp_dll.sln生成dll并修改代码指定路径
